/* This file was generated by SableCC (http://www.sablecc.org/). */

package parser;

import node.*;
import analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTrue(@SuppressWarnings("unused") TTrue node)
    {
        this.index = 0;
    }

    @Override
    public void caseTFalse(@SuppressWarnings("unused") TFalse node)
    {
        this.index = 1;
    }

    @Override
    public void caseTConstant(@SuppressWarnings("unused") TConstant node)
    {
        this.index = 2;
    }

    @Override
    public void caseTFunction(@SuppressWarnings("unused") TFunction node)
    {
        this.index = 3;
    }

    @Override
    public void caseTInt(@SuppressWarnings("unused") TInt node)
    {
        this.index = 4;
    }

    @Override
    public void caseTBool(@SuppressWarnings("unused") TBool node)
    {
        this.index = 5;
    }

    @Override
    public void caseTReal(@SuppressWarnings("unused") TReal node)
    {
        this.index = 6;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 7;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 8;
    }

    @Override
    public void caseTThen(@SuppressWarnings("unused") TThen node)
    {
        this.index = 9;
    }

    @Override
    public void caseTTkLambda(@SuppressWarnings("unused") TTkLambda node)
    {
        this.index = 10;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 11;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 12;
    }

    @Override
    public void caseTEntry(@SuppressWarnings("unused") TEntry node)
    {
        this.index = 13;
    }

    @Override
    public void caseTLeftParentheses(@SuppressWarnings("unused") TLeftParentheses node)
    {
        this.index = 14;
    }

    @Override
    public void caseTRightParentheses(@SuppressWarnings("unused") TRightParentheses node)
    {
        this.index = 15;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 16;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 17;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 18;
    }

    @Override
    public void caseTDivide(@SuppressWarnings("unused") TDivide node)
    {
        this.index = 19;
    }

    @Override
    public void caseTProduct(@SuppressWarnings("unused") TProduct node)
    {
        this.index = 20;
    }

    @Override
    public void caseTModule(@SuppressWarnings("unused") TModule node)
    {
        this.index = 21;
    }

    @Override
    public void caseTExclamation(@SuppressWarnings("unused") TExclamation node)
    {
        this.index = 22;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 23;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 24;
    }

    @Override
    public void caseTMinor(@SuppressWarnings("unused") TMinor node)
    {
        this.index = 25;
    }

    @Override
    public void caseTBigger(@SuppressWarnings("unused") TBigger node)
    {
        this.index = 26;
    }

    @Override
    public void caseTLeftBracket(@SuppressWarnings("unused") TLeftBracket node)
    {
        this.index = 27;
    }

    @Override
    public void caseTRightBracket(@SuppressWarnings("unused") TRightBracket node)
    {
        this.index = 28;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 29;
    }

    @Override
    public void caseTPower(@SuppressWarnings("unused") TPower node)
    {
        this.index = 30;
    }

    @Override
    public void caseTIntHexadecimal(@SuppressWarnings("unused") TIntHexadecimal node)
    {
        this.index = 31;
    }

    @Override
    public void caseTIntDecimal(@SuppressWarnings("unused") TIntDecimal node)
    {
        this.index = 32;
    }

    @Override
    public void caseTFloat(@SuppressWarnings("unused") TFloat node)
    {
        this.index = 33;
    }

    @Override
    public void caseTCientificNotation(@SuppressWarnings("unused") TCientificNotation node)
    {
        this.index = 34;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 35;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 36;
    }
}
