/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.analysis;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATkReservedEntryFunctionDec(ATkReservedEntryFunctionDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkCommentLine(TTkCommentLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkCommentMultiLine(TTkCommentMultiLine node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedEntry(TTkReservedEntry node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedFunction(TTkReservedFunction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedConst(TTkReservedConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedTypeInt(TTkReservedTypeInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedTypeBool(TTkReservedTypeBool node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedTypeReal(TTkReservedTypeReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedBoolTrue(TTkReservedBoolTrue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedBoolFalse(TTkReservedBoolFalse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedBoolAnd(TTkReservedBoolAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedBoolOr(TTkReservedBoolOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedIf(TTkReservedIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedThen(TTkReservedThen node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedElse(TTkReservedElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkReservedLambda(TTkReservedLambda node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkNumberIntegerDec(TTkNumberIntegerDec node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkNumberIntegerHex(TTkNumberIntegerHex node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkNumberFloat(TTkNumberFloat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkNumberFloatCientificNotation(TTkNumberFloatCientificNotation node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignPlus(TTkSignPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignMinus(TTkSignMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignMult(TTkSignMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignDiv(TTkSignDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignMod(TTkSignMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignColon(TTkSignColon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignComma(TTkSignComma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignExclamation(TTkSignExclamation node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignParOpen(TTkSignParOpen node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignParClose(TTkSignParClose node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignBoolEqual(TTkSignBoolEqual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignBoolGt(TTkSignBoolGt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkSignBoolLt(TTkSignBoolLt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkBlank(TTkBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTkId(TTkId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
