/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.analysis;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPProgram().apply(this);
        outStart(node);
    }

    public void inAProgram(AProgram node)
    {
        defaultIn(node);
    }

    public void outAProgram(AProgram node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgram(AProgram node)
    {
        inAProgram(node);
        if(node.getFunctionDec() != null)
        {
            node.getFunctionDec().apply(this);
        }
        outAProgram(node);
    }

    public void inATkReservedEntryFunctionDec(ATkReservedEntryFunctionDec node)
    {
        defaultIn(node);
    }

    public void outATkReservedEntryFunctionDec(ATkReservedEntryFunctionDec node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATkReservedEntryFunctionDec(ATkReservedEntryFunctionDec node)
    {
        inATkReservedEntryFunctionDec(node);
        outATkReservedEntryFunctionDec(node);
    }
}
