/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AABlocExp extends PABlocExp
{
    private final LinkedList<PADecCons> _aDecCons_ = new LinkedList<PADecCons>();
    private PAExp _aExp_;

    public AABlocExp()
    {
        // Constructor
    }

    public AABlocExp(
        @SuppressWarnings("hiding") List<?> _aDecCons_,
        @SuppressWarnings("hiding") PAExp _aExp_)
    {
        // Constructor
        setADecCons(_aDecCons_);

        setAExp(_aExp_);

    }

    @Override
    public Object clone()
    {
        return new AABlocExp(
            cloneList(this._aDecCons_),
            cloneNode(this._aExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAABlocExp(this);
    }

    public LinkedList<PADecCons> getADecCons()
    {
        return this._aDecCons_;
    }

    public void setADecCons(List<?> list)
    {
        for(PADecCons e : this._aDecCons_)
        {
            e.parent(null);
        }
        this._aDecCons_.clear();

        for(Object obj_e : list)
        {
            PADecCons e = (PADecCons) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aDecCons_.add(e);
        }
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aDecCons_)
            + toString(this._aExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aDecCons_.remove(child))
        {
            return;
        }

        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PADecCons> i = this._aDecCons_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PADecCons) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
