/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AAExpList extends PAExpList
{
    private PAExp _aExp_;
    private final LinkedList<PAExpListAux> _aExpListAux_ = new LinkedList<PAExpListAux>();

    public AAExpList()
    {
        // Constructor
    }

    public AAExpList(
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") List<?> _aExpListAux_)
    {
        // Constructor
        setAExp(_aExp_);

        setAExpListAux(_aExpListAux_);

    }

    @Override
    public Object clone()
    {
        return new AAExpList(
            cloneNode(this._aExp_),
            cloneList(this._aExpListAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAExpList(this);
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public LinkedList<PAExpListAux> getAExpListAux()
    {
        return this._aExpListAux_;
    }

    public void setAExpListAux(List<?> list)
    {
        for(PAExpListAux e : this._aExpListAux_)
        {
            e.parent(null);
        }
        this._aExpListAux_.clear();

        for(Object obj_e : list)
        {
            PAExpListAux e = (PAExpListAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aExpListAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aExp_)
            + toString(this._aExpListAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._aExpListAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        for(ListIterator<PAExpListAux> i = this._aExpListAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExpListAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
