/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AAFunctionCallAExp extends PAExp
{
    private PAFunctionCall _aFunctionCall_;

    public AAFunctionCallAExp()
    {
        // Constructor
    }

    public AAFunctionCallAExp(
        @SuppressWarnings("hiding") PAFunctionCall _aFunctionCall_)
    {
        // Constructor
        setAFunctionCall(_aFunctionCall_);

    }

    @Override
    public Object clone()
    {
        return new AAFunctionCallAExp(
            cloneNode(this._aFunctionCall_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAFunctionCallAExp(this);
    }

    public PAFunctionCall getAFunctionCall()
    {
        return this._aFunctionCall_;
    }

    public void setAFunctionCall(PAFunctionCall node)
    {
        if(this._aFunctionCall_ != null)
        {
            this._aFunctionCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aFunctionCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aFunctionCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aFunctionCall_ == child)
        {
            this._aFunctionCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aFunctionCall_ == oldChild)
        {
            setAFunctionCall((PAFunctionCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
