/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AAId extends PAId
{
    private TTkId _tkId_;

    public AAId()
    {
        // Constructor
    }

    public AAId(
        @SuppressWarnings("hiding") TTkId _tkId_)
    {
        // Constructor
        setTkId(_tkId_);

    }

    @Override
    public Object clone()
    {
        return new AAId(
            cloneNode(this._tkId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAId(this);
    }

    public TTkId getTkId()
    {
        return this._tkId_;
    }

    public void setTkId(TTkId node)
    {
        if(this._tkId_ != null)
        {
            this._tkId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkId_ == child)
        {
            this._tkId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkId_ == oldChild)
        {
            setTkId((TTkId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
