/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AALambdaAExp extends PAExp
{
    private PALambda _aLambda_;

    public AALambdaAExp()
    {
        // Constructor
    }

    public AALambdaAExp(
        @SuppressWarnings("hiding") PALambda _aLambda_)
    {
        // Constructor
        setALambda(_aLambda_);

    }

    @Override
    public Object clone()
    {
        return new AALambdaAExp(
            cloneNode(this._aLambda_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAALambdaAExp(this);
    }

    public PALambda getALambda()
    {
        return this._aLambda_;
    }

    public void setALambda(PALambda node)
    {
        if(this._aLambda_ != null)
        {
            this._aLambda_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aLambda_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aLambda_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aLambda_ == child)
        {
            this._aLambda_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aLambda_ == oldChild)
        {
            setALambda((PALambda) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
