/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AALiteralAExp extends PAExp
{
    private PALiteral _aLiteral_;

    public AALiteralAExp()
    {
        // Constructor
    }

    public AALiteralAExp(
        @SuppressWarnings("hiding") PALiteral _aLiteral_)
    {
        // Constructor
        setALiteral(_aLiteral_);

    }

    @Override
    public Object clone()
    {
        return new AALiteralAExp(
            cloneNode(this._aLiteral_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAALiteralAExp(this);
    }

    public PALiteral getALiteral()
    {
        return this._aLiteral_;
    }

    public void setALiteral(PALiteral node)
    {
        if(this._aLiteral_ != null)
        {
            this._aLiteral_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aLiteral_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aLiteral_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aLiteral_ == child)
        {
            this._aLiteral_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aLiteral_ == oldChild)
        {
            setALiteral((PALiteral) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
