/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AAParametersSignature extends PAParametersSignature
{
    private PAParameterSignature _aParameterSignature_;
    private final LinkedList<PAParametersSignatureAux> _aParametersSignatureAux_ = new LinkedList<PAParametersSignatureAux>();

    public AAParametersSignature()
    {
        // Constructor
    }

    public AAParametersSignature(
        @SuppressWarnings("hiding") PAParameterSignature _aParameterSignature_,
        @SuppressWarnings("hiding") List<?> _aParametersSignatureAux_)
    {
        // Constructor
        setAParameterSignature(_aParameterSignature_);

        setAParametersSignatureAux(_aParametersSignatureAux_);

    }

    @Override
    public Object clone()
    {
        return new AAParametersSignature(
            cloneNode(this._aParameterSignature_),
            cloneList(this._aParametersSignatureAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAParametersSignature(this);
    }

    public PAParameterSignature getAParameterSignature()
    {
        return this._aParameterSignature_;
    }

    public void setAParameterSignature(PAParameterSignature node)
    {
        if(this._aParameterSignature_ != null)
        {
            this._aParameterSignature_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aParameterSignature_ = node;
    }

    public LinkedList<PAParametersSignatureAux> getAParametersSignatureAux()
    {
        return this._aParametersSignatureAux_;
    }

    public void setAParametersSignatureAux(List<?> list)
    {
        for(PAParametersSignatureAux e : this._aParametersSignatureAux_)
        {
            e.parent(null);
        }
        this._aParametersSignatureAux_.clear();

        for(Object obj_e : list)
        {
            PAParametersSignatureAux e = (PAParametersSignatureAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aParametersSignatureAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aParameterSignature_)
            + toString(this._aParametersSignatureAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aParameterSignature_ == child)
        {
            this._aParameterSignature_ = null;
            return;
        }

        if(this._aParametersSignatureAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aParameterSignature_ == oldChild)
        {
            setAParameterSignature((PAParameterSignature) newChild);
            return;
        }

        for(ListIterator<PAParametersSignatureAux> i = this._aParametersSignatureAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAParametersSignatureAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
