/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AAProgram extends PAProgram
{
    private final LinkedList<PAFunctionDec> _aFunctionDec_ = new LinkedList<PAFunctionDec>();

    public AAProgram()
    {
        // Constructor
    }

    public AAProgram(
        @SuppressWarnings("hiding") List<?> _aFunctionDec_)
    {
        // Constructor
        setAFunctionDec(_aFunctionDec_);

    }

    @Override
    public Object clone()
    {
        return new AAProgram(
            cloneList(this._aFunctionDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAProgram(this);
    }

    public LinkedList<PAFunctionDec> getAFunctionDec()
    {
        return this._aFunctionDec_;
    }

    public void setAFunctionDec(List<?> list)
    {
        for(PAFunctionDec e : this._aFunctionDec_)
        {
            e.parent(null);
        }
        this._aFunctionDec_.clear();

        for(Object obj_e : list)
        {
            PAFunctionDec e = (PAFunctionDec) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aFunctionDec_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aFunctionDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aFunctionDec_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAFunctionDec> i = this._aFunctionDec_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAFunctionDec) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
