/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanValueLiteral extends PLiteral
{
    private PBooleanValue _booleanValue_;

    public ABooleanValueLiteral()
    {
        // Constructor
    }

    public ABooleanValueLiteral(
        @SuppressWarnings("hiding") PBooleanValue _booleanValue_)
    {
        // Constructor
        setBooleanValue(_booleanValue_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanValueLiteral(
            cloneNode(this._booleanValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanValueLiteral(this);
    }

    public PBooleanValue getBooleanValue()
    {
        return this._booleanValue_;
    }

    public void setBooleanValue(PBooleanValue node)
    {
        if(this._booleanValue_ != null)
        {
            this._booleanValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanValue_ == child)
        {
            this._booleanValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanValue_ == oldChild)
        {
            setBooleanValue((PBooleanValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
