/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AGtExp extends PExp
{
    private PExp _exp_;
    private TTkSignBoolGt _tkSignBoolGt_;
    private POp _op_;

    public AGtExp()
    {
        // Constructor
    }

    public AGtExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TTkSignBoolGt _tkSignBoolGt_,
        @SuppressWarnings("hiding") POp _op_)
    {
        // Constructor
        setExp(_exp_);

        setTkSignBoolGt(_tkSignBoolGt_);

        setOp(_op_);

    }

    @Override
    public Object clone()
    {
        return new AGtExp(
            cloneNode(this._exp_),
            cloneNode(this._tkSignBoolGt_),
            cloneNode(this._op_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TTkSignBoolGt getTkSignBoolGt()
    {
        return this._tkSignBoolGt_;
    }

    public void setTkSignBoolGt(TTkSignBoolGt node)
    {
        if(this._tkSignBoolGt_ != null)
        {
            this._tkSignBoolGt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkSignBoolGt_ = node;
    }

    public POp getOp()
    {
        return this._op_;
    }

    public void setOp(POp node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._tkSignBoolGt_)
            + toString(this._op_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._tkSignBoolGt_ == child)
        {
            this._tkSignBoolGt_ = null;
            return;
        }

        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._tkSignBoolGt_ == oldChild)
        {
            setTkSignBoolGt((TTkSignBoolGt) newChild);
            return;
        }

        if(this._op_ == oldChild)
        {
            setOp((POp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
