/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AIdListAux extends PIdListAux
{
    private TTkSignComma _tkSignComma_;
    private TTkId _tkId_;

    public AIdListAux()
    {
        // Constructor
    }

    public AIdListAux(
        @SuppressWarnings("hiding") TTkSignComma _tkSignComma_,
        @SuppressWarnings("hiding") TTkId _tkId_)
    {
        // Constructor
        setTkSignComma(_tkSignComma_);

        setTkId(_tkId_);

    }

    @Override
    public Object clone()
    {
        return new AIdListAux(
            cloneNode(this._tkSignComma_),
            cloneNode(this._tkId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdListAux(this);
    }

    public TTkSignComma getTkSignComma()
    {
        return this._tkSignComma_;
    }

    public void setTkSignComma(TTkSignComma node)
    {
        if(this._tkSignComma_ != null)
        {
            this._tkSignComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkSignComma_ = node;
    }

    public TTkId getTkId()
    {
        return this._tkId_;
    }

    public void setTkId(TTkId node)
    {
        if(this._tkId_ != null)
        {
            this._tkId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkId_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkSignComma_)
            + toString(this._tkId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkSignComma_ == child)
        {
            this._tkSignComma_ = null;
            return;
        }

        if(this._tkId_ == child)
        {
            this._tkId_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkSignComma_ == oldChild)
        {
            setTkSignComma((TTkSignComma) newChild);
            return;
        }

        if(this._tkId_ == oldChild)
        {
            setTkId((TTkId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
