/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AIdList extends PIdList
{
    private TTkId _tkId_;
    private final LinkedList<PIdListAux> _idListAux_ = new LinkedList<PIdListAux>();

    public AIdList()
    {
        // Constructor
    }

    public AIdList(
        @SuppressWarnings("hiding") TTkId _tkId_,
        @SuppressWarnings("hiding") List<?> _idListAux_)
    {
        // Constructor
        setTkId(_tkId_);

        setIdListAux(_idListAux_);

    }

    @Override
    public Object clone()
    {
        return new AIdList(
            cloneNode(this._tkId_),
            cloneList(this._idListAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdList(this);
    }

    public TTkId getTkId()
    {
        return this._tkId_;
    }

    public void setTkId(TTkId node)
    {
        if(this._tkId_ != null)
        {
            this._tkId_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkId_ = node;
    }

    public LinkedList<PIdListAux> getIdListAux()
    {
        return this._idListAux_;
    }

    public void setIdListAux(List<?> list)
    {
        for(PIdListAux e : this._idListAux_)
        {
            e.parent(null);
        }
        this._idListAux_.clear();

        for(Object obj_e : list)
        {
            PIdListAux e = (PIdListAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._idListAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkId_)
            + toString(this._idListAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkId_ == child)
        {
            this._tkId_ = null;
            return;
        }

        if(this._idListAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkId_ == oldChild)
        {
            setTkId((TTkId) newChild);
            return;
        }

        for(ListIterator<PIdListAux> i = this._idListAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIdListAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
