/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AIfStmtElseAux extends PIfStmtElseAux
{
    private TTkReservedElse _tkReservedElse_;
    private PTerm _term_;

    public AIfStmtElseAux()
    {
        // Constructor
    }

    public AIfStmtElseAux(
        @SuppressWarnings("hiding") TTkReservedElse _tkReservedElse_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setTkReservedElse(_tkReservedElse_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new AIfStmtElseAux(
            cloneNode(this._tkReservedElse_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStmtElseAux(this);
    }

    public TTkReservedElse getTkReservedElse()
    {
        return this._tkReservedElse_;
    }

    public void setTkReservedElse(TTkReservedElse node)
    {
        if(this._tkReservedElse_ != null)
        {
            this._tkReservedElse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkReservedElse_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkReservedElse_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkReservedElse_ == child)
        {
            this._tkReservedElse_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkReservedElse_ == oldChild)
        {
            setTkReservedElse((TTkReservedElse) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
