/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ANegFactor extends PFactor
{
    private PNegation _negation_;

    public ANegFactor()
    {
        // Constructor
    }

    public ANegFactor(
        @SuppressWarnings("hiding") PNegation _negation_)
    {
        // Constructor
        setNegation(_negation_);

    }

    @Override
    public Object clone()
    {
        return new ANegFactor(
            cloneNode(this._negation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegFactor(this);
    }

    public PNegation getNegation()
    {
        return this._negation_;
    }

    public void setNegation(PNegation node)
    {
        if(this._negation_ != null)
        {
            this._negation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negation_ == child)
        {
            this._negation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negation_ == oldChild)
        {
            setNegation((PNegation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
