/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ANegation extends PNegation
{
    private TTkSignMinus _tkSignMinus_;
    private PTerm _term_;

    public ANegation()
    {
        // Constructor
    }

    public ANegation(
        @SuppressWarnings("hiding") TTkSignMinus _tkSignMinus_,
        @SuppressWarnings("hiding") PTerm _term_)
    {
        // Constructor
        setTkSignMinus(_tkSignMinus_);

        setTerm(_term_);

    }

    @Override
    public Object clone()
    {
        return new ANegation(
            cloneNode(this._tkSignMinus_),
            cloneNode(this._term_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegation(this);
    }

    public TTkSignMinus getTkSignMinus()
    {
        return this._tkSignMinus_;
    }

    public void setTkSignMinus(TTkSignMinus node)
    {
        if(this._tkSignMinus_ != null)
        {
            this._tkSignMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkSignMinus_ = node;
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkSignMinus_)
            + toString(this._term_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkSignMinus_ == child)
        {
            this._tkSignMinus_ = null;
            return;
        }

        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkSignMinus_ == oldChild)
        {
            setTkSignMinus((TTkSignMinus) newChild);
            return;
        }

        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
