/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ANegBoolExp extends PExp
{
    private TTkSignExclamation _tkSignExclamation_;
    private POp _op_;

    public ANegBoolExp()
    {
        // Constructor
    }

    public ANegBoolExp(
        @SuppressWarnings("hiding") TTkSignExclamation _tkSignExclamation_,
        @SuppressWarnings("hiding") POp _op_)
    {
        // Constructor
        setTkSignExclamation(_tkSignExclamation_);

        setOp(_op_);

    }

    @Override
    public Object clone()
    {
        return new ANegBoolExp(
            cloneNode(this._tkSignExclamation_),
            cloneNode(this._op_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegBoolExp(this);
    }

    public TTkSignExclamation getTkSignExclamation()
    {
        return this._tkSignExclamation_;
    }

    public void setTkSignExclamation(TTkSignExclamation node)
    {
        if(this._tkSignExclamation_ != null)
        {
            this._tkSignExclamation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkSignExclamation_ = node;
    }

    public POp getOp()
    {
        return this._op_;
    }

    public void setOp(POp node)
    {
        if(this._op_ != null)
        {
            this._op_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._op_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkSignExclamation_)
            + toString(this._op_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkSignExclamation_ == child)
        {
            this._tkSignExclamation_ = null;
            return;
        }

        if(this._op_ == child)
        {
            this._op_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkSignExclamation_ == oldChild)
        {
            setTkSignExclamation((TTkSignExclamation) newChild);
            return;
        }

        if(this._op_ == oldChild)
        {
            setOp((POp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
