/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ANumeralIntAExp extends PAExp
{
    private PANumeralInt _aNumeralInt_;

    public ANumeralIntAExp()
    {
        // Constructor
    }

    public ANumeralIntAExp(
        @SuppressWarnings("hiding") PANumeralInt _aNumeralInt_)
    {
        // Constructor
        setANumeralInt(_aNumeralInt_);

    }

    @Override
    public Object clone()
    {
        return new ANumeralIntAExp(
            cloneNode(this._aNumeralInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeralIntAExp(this);
    }

    public PANumeralInt getANumeralInt()
    {
        return this._aNumeralInt_;
    }

    public void setANumeralInt(PANumeralInt node)
    {
        if(this._aNumeralInt_ != null)
        {
            this._aNumeralInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aNumeralInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aNumeralInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aNumeralInt_ == child)
        {
            this._aNumeralInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aNumeralInt_ == oldChild)
        {
            setANumeralInt((PANumeralInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
