/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ANumeralFloatLiteral extends PLiteral
{
    private PNumeralFloat _numeralFloat_;

    public ANumeralFloatLiteral()
    {
        // Constructor
    }

    public ANumeralFloatLiteral(
        @SuppressWarnings("hiding") PNumeralFloat _numeralFloat_)
    {
        // Constructor
        setNumeralFloat(_numeralFloat_);

    }

    @Override
    public Object clone()
    {
        return new ANumeralFloatLiteral(
            cloneNode(this._numeralFloat_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeralFloatLiteral(this);
    }

    public PNumeralFloat getNumeralFloat()
    {
        return this._numeralFloat_;
    }

    public void setNumeralFloat(PNumeralFloat node)
    {
        if(this._numeralFloat_ != null)
        {
            this._numeralFloat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeralFloat_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeralFloat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeralFloat_ == child)
        {
            this._numeralFloat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeralFloat_ == oldChild)
        {
            setNumeralFloat((PNumeralFloat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
