/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ANumeralIntLiteral extends PLiteral
{
    private PNumeralInt _numeralInt_;

    public ANumeralIntLiteral()
    {
        // Constructor
    }

    public ANumeralIntLiteral(
        @SuppressWarnings("hiding") PNumeralInt _numeralInt_)
    {
        // Constructor
        setNumeralInt(_numeralInt_);

    }

    @Override
    public Object clone()
    {
        return new ANumeralIntLiteral(
            cloneNode(this._numeralInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeralIntLiteral(this);
    }

    public PNumeralInt getNumeralInt()
    {
        return this._numeralInt_;
    }

    public void setNumeralInt(PNumeralInt node)
    {
        if(this._numeralInt_ != null)
        {
            this._numeralInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeralInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numeralInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numeralInt_ == child)
        {
            this._numeralInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numeralInt_ == oldChild)
        {
            setNumeralInt((PNumeralInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
