/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AParameters extends PParameters
{
    private PParameter _parameter_;
    private final LinkedList<PParametersAux> _parametersAux_ = new LinkedList<PParametersAux>();

    public AParameters()
    {
        // Constructor
    }

    public AParameters(
        @SuppressWarnings("hiding") PParameter _parameter_,
        @SuppressWarnings("hiding") List<?> _parametersAux_)
    {
        // Constructor
        setParameter(_parameter_);

        setParametersAux(_parametersAux_);

    }

    @Override
    public Object clone()
    {
        return new AParameters(
            cloneNode(this._parameter_),
            cloneList(this._parametersAux_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameters(this);
    }

    public PParameter getParameter()
    {
        return this._parameter_;
    }

    public void setParameter(PParameter node)
    {
        if(this._parameter_ != null)
        {
            this._parameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parameter_ = node;
    }

    public LinkedList<PParametersAux> getParametersAux()
    {
        return this._parametersAux_;
    }

    public void setParametersAux(List<?> list)
    {
        for(PParametersAux e : this._parametersAux_)
        {
            e.parent(null);
        }
        this._parametersAux_.clear();

        for(Object obj_e : list)
        {
            PParametersAux e = (PParametersAux) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parametersAux_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parameter_)
            + toString(this._parametersAux_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parameter_ == child)
        {
            this._parameter_ = null;
            return;
        }

        if(this._parametersAux_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parameter_ == oldChild)
        {
            setParameter((PParameter) newChild);
            return;
        }

        for(ListIterator<PParametersAux> i = this._parametersAux_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametersAux) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
