/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import java.util.*;
import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PFunctionDec> _functionDec_ = new LinkedList<PFunctionDec>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _functionDec_)
    {
        // Constructor
        setFunctionDec(_functionDec_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._functionDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PFunctionDec> getFunctionDec()
    {
        return this._functionDec_;
    }

    public void setFunctionDec(List<?> list)
    {
        for(PFunctionDec e : this._functionDec_)
        {
            e.parent(null);
        }
        this._functionDec_.clear();

        for(Object obj_e : list)
        {
            PFunctionDec e = (PFunctionDec) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._functionDec_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionDec_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PFunctionDec> i = this._functionDec_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PFunctionDec) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
