/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private PFunctionDec _functionDec_;

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") PFunctionDec _functionDec_)
    {
        // Constructor
        setFunctionDec(_functionDec_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneNode(this._functionDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public PFunctionDec getFunctionDec()
    {
        return this._functionDec_;
    }

    public void setFunctionDec(PFunctionDec node)
    {
        if(this._functionDec_ != null)
        {
            this._functionDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionDec_ == child)
        {
            this._functionDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionDec_ == oldChild)
        {
            setFunctionDec((PFunctionDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
