/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ATkNumberFloatNumeralFloat extends PNumeralFloat
{
    private TTkNumberFloat _tkNumberFloat_;

    public ATkNumberFloatNumeralFloat()
    {
        // Constructor
    }

    public ATkNumberFloatNumeralFloat(
        @SuppressWarnings("hiding") TTkNumberFloat _tkNumberFloat_)
    {
        // Constructor
        setTkNumberFloat(_tkNumberFloat_);

    }

    @Override
    public Object clone()
    {
        return new ATkNumberFloatNumeralFloat(
            cloneNode(this._tkNumberFloat_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATkNumberFloatNumeralFloat(this);
    }

    public TTkNumberFloat getTkNumberFloat()
    {
        return this._tkNumberFloat_;
    }

    public void setTkNumberFloat(TTkNumberFloat node)
    {
        if(this._tkNumberFloat_ != null)
        {
            this._tkNumberFloat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkNumberFloat_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkNumberFloat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkNumberFloat_ == child)
        {
            this._tkNumberFloat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkNumberFloat_ == oldChild)
        {
            setTkNumberFloat((TTkNumberFloat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
