/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ATkNumberFloatCientificNotationNumeralFloat extends PNumeralFloat
{
    private TTkNumberFloatCientificNotation _tkNumberFloatCientificNotation_;

    public ATkNumberFloatCientificNotationNumeralFloat()
    {
        // Constructor
    }

    public ATkNumberFloatCientificNotationNumeralFloat(
        @SuppressWarnings("hiding") TTkNumberFloatCientificNotation _tkNumberFloatCientificNotation_)
    {
        // Constructor
        setTkNumberFloatCientificNotation(_tkNumberFloatCientificNotation_);

    }

    @Override
    public Object clone()
    {
        return new ATkNumberFloatCientificNotationNumeralFloat(
            cloneNode(this._tkNumberFloatCientificNotation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATkNumberFloatCientificNotationNumeralFloat(this);
    }

    public TTkNumberFloatCientificNotation getTkNumberFloatCientificNotation()
    {
        return this._tkNumberFloatCientificNotation_;
    }

    public void setTkNumberFloatCientificNotation(TTkNumberFloatCientificNotation node)
    {
        if(this._tkNumberFloatCientificNotation_ != null)
        {
            this._tkNumberFloatCientificNotation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkNumberFloatCientificNotation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkNumberFloatCientificNotation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkNumberFloatCientificNotation_ == child)
        {
            this._tkNumberFloatCientificNotation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkNumberFloatCientificNotation_ == oldChild)
        {
            setTkNumberFloatCientificNotation((TTkNumberFloatCientificNotation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
