/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ATkReservedEntryFunctionDec extends PFunctionDec
{

    public ATkReservedEntryFunctionDec()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ATkReservedEntryFunctionDec();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATkReservedEntryFunctionDec(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
