/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class ATkReservedTypeIntType extends PType
{
    private TTkReservedTypeInt _tkReservedTypeInt_;

    public ATkReservedTypeIntType()
    {
        // Constructor
    }

    public ATkReservedTypeIntType(
        @SuppressWarnings("hiding") TTkReservedTypeInt _tkReservedTypeInt_)
    {
        // Constructor
        setTkReservedTypeInt(_tkReservedTypeInt_);

    }

    @Override
    public Object clone()
    {
        return new ATkReservedTypeIntType(
            cloneNode(this._tkReservedTypeInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATkReservedTypeIntType(this);
    }

    public TTkReservedTypeInt getTkReservedTypeInt()
    {
        return this._tkReservedTypeInt_;
    }

    public void setTkReservedTypeInt(TTkReservedTypeInt node)
    {
        if(this._tkReservedTypeInt_ != null)
        {
            this._tkReservedTypeInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tkReservedTypeInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tkReservedTypeInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tkReservedTypeInt_ == child)
        {
            this._tkReservedTypeInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tkReservedTypeInt_ == oldChild)
        {
            setTkReservedTypeInt((TTkReservedTypeInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
