/* This file was generated by SableCC (http://www.sablecc.org/). */

package br.ufs.dcomp.compilers.project.nonneumann.node;

import br.ufs.dcomp.compilers.project.nonneumann.analysis.*;

@SuppressWarnings("nls")
public final class TReservedBoolTrue extends Token
{
    public TReservedBoolTrue()
    {
        super.setText("true");
    }

    public TReservedBoolTrue(int line, int pos)
    {
        super.setText("true");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TReservedBoolTrue(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTReservedBoolTrue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TReservedBoolTrue text.");
    }
}
