/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAAssignFunctionAParameterAssign extends PAParameterAssign
{
    private PAAssignFunction _aAssignFunction_;

    public AAAssignFunctionAParameterAssign()
    {
        // Constructor
    }

    public AAAssignFunctionAParameterAssign(
        @SuppressWarnings("hiding") PAAssignFunction _aAssignFunction_)
    {
        // Constructor
        setAAssignFunction(_aAssignFunction_);

    }

    @Override
    public Object clone()
    {
        return new AAAssignFunctionAParameterAssign(
            cloneNode(this._aAssignFunction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAAssignFunctionAParameterAssign(this);
    }

    public PAAssignFunction getAAssignFunction()
    {
        return this._aAssignFunction_;
    }

    public void setAAssignFunction(PAAssignFunction node)
    {
        if(this._aAssignFunction_ != null)
        {
            this._aAssignFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aAssignFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aAssignFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aAssignFunction_ == child)
        {
            this._aAssignFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aAssignFunction_ == oldChild)
        {
            setAAssignFunction((PAAssignFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
