/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AABlockExpressionAExpression extends PAExpression
{
    private PABlockExpression _aBlockExpression_;

    public AABlockExpressionAExpression()
    {
        // Constructor
    }

    public AABlockExpressionAExpression(
        @SuppressWarnings("hiding") PABlockExpression _aBlockExpression_)
    {
        // Constructor
        setABlockExpression(_aBlockExpression_);

    }

    @Override
    public Object clone()
    {
        return new AABlockExpressionAExpression(
            cloneNode(this._aBlockExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAABlockExpressionAExpression(this);
    }

    public PABlockExpression getABlockExpression()
    {
        return this._aBlockExpression_;
    }

    public void setABlockExpression(PABlockExpression node)
    {
        if(this._aBlockExpression_ != null)
        {
            this._aBlockExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aBlockExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aBlockExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aBlockExpression_ == child)
        {
            this._aBlockExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aBlockExpression_ == oldChild)
        {
            setABlockExpression((PABlockExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
