/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AACallFunctionAExpression extends PAExpression
{
    private PACallFunction _aCallFunction_;

    public AACallFunctionAExpression()
    {
        // Constructor
    }

    public AACallFunctionAExpression(
        @SuppressWarnings("hiding") PACallFunction _aCallFunction_)
    {
        // Constructor
        setACallFunction(_aCallFunction_);

    }

    @Override
    public Object clone()
    {
        return new AACallFunctionAExpression(
            cloneNode(this._aCallFunction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAACallFunctionAExpression(this);
    }

    public PACallFunction getACallFunction()
    {
        return this._aCallFunction_;
    }

    public void setACallFunction(PACallFunction node)
    {
        if(this._aCallFunction_ != null)
        {
            this._aCallFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aCallFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aCallFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aCallFunction_ == child)
        {
            this._aCallFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aCallFunction_ == oldChild)
        {
            setACallFunction((PACallFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
