/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AACientificNotationAExpression extends PAExpression
{
    private TCientificNotation _cientificNotation_;

    public AACientificNotationAExpression()
    {
        // Constructor
    }

    public AACientificNotationAExpression(
        @SuppressWarnings("hiding") TCientificNotation _cientificNotation_)
    {
        // Constructor
        setCientificNotation(_cientificNotation_);

    }

    @Override
    public Object clone()
    {
        return new AACientificNotationAExpression(
            cloneNode(this._cientificNotation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAACientificNotationAExpression(this);
    }

    public TCientificNotation getCientificNotation()
    {
        return this._cientificNotation_;
    }

    public void setCientificNotation(TCientificNotation node)
    {
        if(this._cientificNotation_ != null)
        {
            this._cientificNotation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cientificNotation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cientificNotation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cientificNotation_ == child)
        {
            this._cientificNotation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cientificNotation_ == oldChild)
        {
            setCientificNotation((TCientificNotation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
