/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AADeclarationConstant extends PADeclarationConstant
{
    private PAType _aType_;
    private PAExpression _aExpression_;

    public AADeclarationConstant()
    {
        // Constructor
    }

    public AADeclarationConstant(
        @SuppressWarnings("hiding") PAType _aType_,
        @SuppressWarnings("hiding") PAExpression _aExpression_)
    {
        // Constructor
        setAType(_aType_);

        setAExpression(_aExpression_);

    }

    @Override
    public Object clone()
    {
        return new AADeclarationConstant(
            cloneNode(this._aType_),
            cloneNode(this._aExpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAADeclarationConstant(this);
    }

    public PAType getAType()
    {
        return this._aType_;
    }

    public void setAType(PAType node)
    {
        if(this._aType_ != null)
        {
            this._aType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aType_ = node;
    }

    public PAExpression getAExpression()
    {
        return this._aExpression_;
    }

    public void setAExpression(PAExpression node)
    {
        if(this._aExpression_ != null)
        {
            this._aExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aType_)
            + toString(this._aExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aType_ == child)
        {
            this._aType_ = null;
            return;
        }

        if(this._aExpression_ == child)
        {
            this._aExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aType_ == oldChild)
        {
            setAType((PAType) newChild);
            return;
        }

        if(this._aExpression_ == oldChild)
        {
            setAExpression((PAExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
