/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAIfThenElseStatementAExpression extends PAExpression
{
    private PAIfThenElseStatement _aIfThenElseStatement_;

    public AAIfThenElseStatementAExpression()
    {
        // Constructor
    }

    public AAIfThenElseStatementAExpression(
        @SuppressWarnings("hiding") PAIfThenElseStatement _aIfThenElseStatement_)
    {
        // Constructor
        setAIfThenElseStatement(_aIfThenElseStatement_);

    }

    @Override
    public Object clone()
    {
        return new AAIfThenElseStatementAExpression(
            cloneNode(this._aIfThenElseStatement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIfThenElseStatementAExpression(this);
    }

    public PAIfThenElseStatement getAIfThenElseStatement()
    {
        return this._aIfThenElseStatement_;
    }

    public void setAIfThenElseStatement(PAIfThenElseStatement node)
    {
        if(this._aIfThenElseStatement_ != null)
        {
            this._aIfThenElseStatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aIfThenElseStatement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aIfThenElseStatement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aIfThenElseStatement_ == child)
        {
            this._aIfThenElseStatement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aIfThenElseStatement_ == oldChild)
        {
            setAIfThenElseStatement((PAIfThenElseStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
