/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AAIntHexadecimalAExpression extends PAExpression
{
    private TIntHexadecimal _intHexadecimal_;

    public AAIntHexadecimalAExpression()
    {
        // Constructor
    }

    public AAIntHexadecimalAExpression(
        @SuppressWarnings("hiding") TIntHexadecimal _intHexadecimal_)
    {
        // Constructor
        setIntHexadecimal(_intHexadecimal_);

    }

    @Override
    public Object clone()
    {
        return new AAIntHexadecimalAExpression(
            cloneNode(this._intHexadecimal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAIntHexadecimalAExpression(this);
    }

    public TIntHexadecimal getIntHexadecimal()
    {
        return this._intHexadecimal_;
    }

    public void setIntHexadecimal(TIntHexadecimal node)
    {
        if(this._intHexadecimal_ != null)
        {
            this._intHexadecimal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intHexadecimal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intHexadecimal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intHexadecimal_ == child)
        {
            this._intHexadecimal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intHexadecimal_ == oldChild)
        {
            setIntHexadecimal((TIntHexadecimal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
