/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AAListIdentifiers extends PAListIdentifiers
{
    private final LinkedList<PAListIdentifiersSequence> _aListIdentifiersSequence_ = new LinkedList<PAListIdentifiersSequence>();

    public AAListIdentifiers()
    {
        // Constructor
    }

    public AAListIdentifiers(
        @SuppressWarnings("hiding") List<?> _aListIdentifiersSequence_)
    {
        // Constructor
        setAListIdentifiersSequence(_aListIdentifiersSequence_);

    }

    @Override
    public Object clone()
    {
        return new AAListIdentifiers(
            cloneList(this._aListIdentifiersSequence_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAListIdentifiers(this);
    }

    public LinkedList<PAListIdentifiersSequence> getAListIdentifiersSequence()
    {
        return this._aListIdentifiersSequence_;
    }

    public void setAListIdentifiersSequence(List<?> list)
    {
        for(PAListIdentifiersSequence e : this._aListIdentifiersSequence_)
        {
            e.parent(null);
        }
        this._aListIdentifiersSequence_.clear();

        for(Object obj_e : list)
        {
            PAListIdentifiersSequence e = (PAListIdentifiersSequence) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aListIdentifiersSequence_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aListIdentifiersSequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aListIdentifiersSequence_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAListIdentifiersSequence> i = this._aListIdentifiersSequence_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAListIdentifiersSequence) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
