/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AAParameters extends PAParameters
{
    private PAParameter _aParameter_;
    private final LinkedList<PAParametersSequence> _aParametersSequence_ = new LinkedList<PAParametersSequence>();

    public AAParameters()
    {
        // Constructor
    }

    public AAParameters(
        @SuppressWarnings("hiding") PAParameter _aParameter_,
        @SuppressWarnings("hiding") List<?> _aParametersSequence_)
    {
        // Constructor
        setAParameter(_aParameter_);

        setAParametersSequence(_aParametersSequence_);

    }

    @Override
    public Object clone()
    {
        return new AAParameters(
            cloneNode(this._aParameter_),
            cloneList(this._aParametersSequence_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAParameters(this);
    }

    public PAParameter getAParameter()
    {
        return this._aParameter_;
    }

    public void setAParameter(PAParameter node)
    {
        if(this._aParameter_ != null)
        {
            this._aParameter_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aParameter_ = node;
    }

    public LinkedList<PAParametersSequence> getAParametersSequence()
    {
        return this._aParametersSequence_;
    }

    public void setAParametersSequence(List<?> list)
    {
        for(PAParametersSequence e : this._aParametersSequence_)
        {
            e.parent(null);
        }
        this._aParametersSequence_.clear();

        for(Object obj_e : list)
        {
            PAParametersSequence e = (PAParametersSequence) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aParametersSequence_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aParameter_)
            + toString(this._aParametersSequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aParameter_ == child)
        {
            this._aParameter_ = null;
            return;
        }

        if(this._aParametersSequence_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aParameter_ == oldChild)
        {
            setAParameter((PAParameter) newChild);
            return;
        }

        for(ListIterator<PAParametersSequence> i = this._aParametersSequence_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAParametersSequence) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
