/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import java.util.*;
import analysis.*;

@SuppressWarnings("nls")
public final class AAParametersAssign extends PAParametersAssign
{
    private PAParameterAssign _aParameterAssign_;
    private final LinkedList<PAParametersAssignSequence> _aParametersAssignSequence_ = new LinkedList<PAParametersAssignSequence>();

    public AAParametersAssign()
    {
        // Constructor
    }

    public AAParametersAssign(
        @SuppressWarnings("hiding") PAParameterAssign _aParameterAssign_,
        @SuppressWarnings("hiding") List<?> _aParametersAssignSequence_)
    {
        // Constructor
        setAParameterAssign(_aParameterAssign_);

        setAParametersAssignSequence(_aParametersAssignSequence_);

    }

    @Override
    public Object clone()
    {
        return new AAParametersAssign(
            cloneNode(this._aParameterAssign_),
            cloneList(this._aParametersAssignSequence_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAParametersAssign(this);
    }

    public PAParameterAssign getAParameterAssign()
    {
        return this._aParameterAssign_;
    }

    public void setAParameterAssign(PAParameterAssign node)
    {
        if(this._aParameterAssign_ != null)
        {
            this._aParameterAssign_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aParameterAssign_ = node;
    }

    public LinkedList<PAParametersAssignSequence> getAParametersAssignSequence()
    {
        return this._aParametersAssignSequence_;
    }

    public void setAParametersAssignSequence(List<?> list)
    {
        for(PAParametersAssignSequence e : this._aParametersAssignSequence_)
        {
            e.parent(null);
        }
        this._aParametersAssignSequence_.clear();

        for(Object obj_e : list)
        {
            PAParametersAssignSequence e = (PAParametersAssignSequence) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aParametersAssignSequence_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aParameterAssign_)
            + toString(this._aParametersAssignSequence_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aParameterAssign_ == child)
        {
            this._aParameterAssign_ = null;
            return;
        }

        if(this._aParametersAssignSequence_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aParameterAssign_ == oldChild)
        {
            setAParameterAssign((PAParameterAssign) newChild);
            return;
        }

        for(ListIterator<PAParametersAssignSequence> i = this._aParametersAssignSequence_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAParametersAssignSequence) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
