/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TTkLambda extends Token
{
    public TTkLambda()
    {
        super.setText("lambda");
    }

    public TTkLambda(int line, int pos)
    {
        super.setText("lambda");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTkLambda(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTkLambda(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTkLambda text.");
    }
}
